Development
asiimwedismas/youtube-clone pull request #1
Opened 2020-03-25 19:55 UTC by asiimwedismas

Please review this code so we can merge it to the master branch

We couldn't;t figure out how to host a live demo, maybe that's something u will shade some light one

2020-03-25 21:04 UTC, addod19 commented
> Please review this code so we can merge it to the master branch
> 
> We couldn't;t figure out how to host a live demo, maybe that's something u will shade some light one

Navigate to the index.html page on your Github repo and copy the link to this link http://raw.githack.com/. The link will generate development and production link. You can use the development link for your README file live link

2020-03-25 21:04 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-03-25 21:21 UTC, addod19 requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, you have done a great job with this project 👍 Let us improve our project before we move ahead. Kindly address the comments below: 😄 
* The nav is missing 3 images at the rightmost part of the nav
![im](https://user-images.githubusercontent.com/46388113/77586222-b3b47f80-6edd-11ea-8e00-3be51a47eec0.PNG)
* Kindly edit the PR so it describes the purpose of the project or what exactly you did
* We have 1 warning returned by w3validator
* The main video is not playing. It should play
* The overall UI of the project needs improvement. Check this [link](youtube.com) as a reference

Make these changes and submit another code review 🙂 
_Hapy coding_ 👨‍💻 
Daniel Larbi Addo

2020-03-25 21:21 UTC, addod19 commented on index.html
> +        <aside id="thumbnails-aside">
The ```<aside>``` is not to be nested in the main. The aside should take the video previews and the main should have the main video together with the other contents

2020-03-26 14:53 UTC, asiimwedismas commented
Worked on the issues raised @addod19

2020-03-26 19:39 UTC, asiimwedismas commented
The video doesn't seem to be loading on githack but it does on our development machines 
I have also noticed the youtube logo in footer isn't loading but once again, it loaded fine on our development machines

2020-03-27 02:16 UTC, MarioDena approved these changes
Congratulations on implementing the requested changes!

## Project approved! 🥇 

## Code Review by Mario Enrique Delgado Naranjo

2020-03-27 09:24 UTC, merged